### ISSUE TITLE
Bug - citoyen.go

### ISSUE THREAD

**Issue by gcleroux** [gcleroux/IFT630-SCAM#7]
@cimo2801 Je check le code de citoyen et cette ligne la va causer des erreurs selon moi.

`installations` est l'array qui contient tous les noms des batiments dans la ville
On ne peut pas faire un random sur sa longueur, car on pourrait avoir `n > 3` batiments dans la ville, et uniquement 3 types de batiments.
Si on pige un `n >= 3`, on va avoir une erreur d'index

https://github.com/gcleroux/IFT630-SCAM/blob/566173a89e6279e17cd29bdf1d889a97cdd2d2c6/pkg/people/citoyen.go#L46-L47

**Comment by cimo2801** [comment]
Effectivement, je vais corriger ça. Merci!
