### ISSUE TITLE
Utilisation `defer`

### ISSUE THREAD

**Issue by gcleroux** [gcleroux/IFT630-SCAM#9]
@cimo2801 J'ai lu sur les mutex récemment et apparement, faudrait changer une ligne dans ce code là:

https://github.com/gcleroux/IFT630-SCAM/blob/b8fd61115852fabbf372ff69c27910617ed6e4c9/pkg/people/citoyen.go#L17-L28

Il faudrait utiliser le keyword [defer](https://go.dev/tour/flowcontrol/12). La grosse différence avec ce qu'on fait en ce moment, c'est que si la goroutine panic, on va quand même lacher le mutex avant de crash.

```go
func (c *CitoyenLock) Visite() { 
    c.mutex.Lock()
    defer c.mutex.Unlock()
    c.nombreVisite++ 
} 

func (c *CitoyenLock) NombreVisites() int { 
    c.mutex.Lock() 
    defer c.mutex.Unlock() 
    return c.nombreVisite 
} 
```

**Comment by cimo2801** [comment]
C'est fait. J'ai push directement sur la branche First-Logic.
